const i18Obj = {
  en: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    titleWelcome: 'TaskManager',
    descrWelcome:
      "This is a program that helps manage tasks. Plan, manage and track all your team's tasks in one software.",
    titleTeam: 'Our team',
    nameV: 'Viktoria',
    nameA: 'Asel',
    nameD: 'Darya',
    teamContentV: ['Welcome Page', 'Localization'],
    teamContentA: ['Main Page'],
    teamContentD: ['Login forms', 'User authorization'],
    buttonMainPage: 'Go to Main Page',
    buttonEditProfile: 'Edit profile',
    buttonNewBoard: 'new board',
    signOut: 'Sign Out',
    name: 'Name',
    nameError: 'Please,enter name!',
    login: 'Login',
    loginError: 'Please,enter login!',
    password: 'Password',
    passwordError: 'Please,create a password(letters,numbers,min length is 5)!',
    signUpText: 'Already have an account? Sign in',
    signUpAlert: 'User is already registered, go to sign in!',
    signInAlert: 'User is not registered or password is not correct!',
    signInForgetPassword: 'Forgot password?',
    signInText: 'Do not have an account? Sign Up',
    signUpSuccessReg: 'You have successfully registered!',
    backButton: 'Back',
    profileEdit: 'Edit profile',
    profileEditText: 'Data changed successfully!',
    profileDelete: 'Delete profile',
    profileDeleteText: 'Profile deleted successfully!',
    addColumn: 'Add column',
  },
  ru: {
    signIn: 'Вход',
    signUp: 'Регистриция',
    titleWelcome: 'Таск-менеджер',
    descrWelcome:
      'Это программа, которая помогает управлять задачами. Планируйте, управляйте и отслеживайте все задачи вашей команды в одном программном обеспечении.',
    titleTeam: 'Наша команда',
    nameV: 'Виктория',
    nameA: 'Асель',
    nameD: 'Дарья',
    teamContentV: ['Страница приветствия', 'Локализация приложения'],
    teamContentA: ['Главная страница'],
    teamContentD: ['Форма входа/регистрации', 'Aвторизация пользователя'],
    buttonMainPage: 'Главная страница',
    buttonEditProfile: 'Профиль',
    buttonNewBoard: 'Новая доска',
    signOut: 'Выйти',
    name: 'Имя',
    nameError: 'Пожалуйста, введите имя!',
    login: 'Логин',
    loginError: 'Пожалуйста, введите логин!',
    password: 'Пароль',
    passwordError: 'Пожалуйста, придумайте пароль (буквы, цифры, минимальная длина 5 символов)!',
    signUpText: 'У вас уже есть аккаунт? Войти',
    signUpAlert: 'Пользователь уже зарегистрирован, пройдите авторизацию!',
    signInAlert: 'Пользователь не зарегистрирован или введен неверный пароль!',
    signInForgetPassword: 'Забыли пароль?',
    signInText: 'Нет учетной записи? Зарегистрируйтесь',
    signUpSuccessReg: 'Вы успешно зарегистрированы!',
    backButton: 'Назад',
    profileEdit: 'Pедактировать профиль',
    profileEditText: 'Данные успешно изменены!',
    profileDelete: 'Удалить профиль',
    profileDeleteText: 'Профиль успешно удален!',
    addColumn: 'Добавить столбец',
  },
};
export default i18Obj;
