const i18Obj = {
  en: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    boardTitle: 'Your boards',
    boardCreate: 'Create Board',
    boardCount: 'Number of boards: ',
    boardSearchInput: 'Board name',
    boardDescription: 'Description',
    titleWelcome: 'TaskManager',
    descrWelcome:
      "This is a program that helps manage tasks. Plan, manage and track all your team's tasks in one software.",
    titleTeam: 'Our team',
    nameV: 'Viktoria',
    nameA: 'Asel',
    nameD: 'Darya',
    buttonMainPage: 'Go to Main Page',
    buttonEditProfile: 'Edit profile',
    buttonNewBoard: 'new board',
    signOut: 'Sign Out',
  },
  ru: {
    signIn: 'Вход',
    signUp: 'Регистриция',
    boardTitle: 'Ваши доски',
    boardCreate: 'Создать доску',
    boardCount: 'Количество досек: ',
    boardSearchInput: 'Название доски',
    boardDescription: 'Описание ',
    titleWelcome: 'Таск-менеджер',
    descrWelcome:
      'Это программа, которая помогает управлять задачами. Планируйте, управляйте и отслеживайте все задачи вашей команды в одном программном обеспечении.',
    titleTeam: 'Наша команда',
    nameV: 'Виктория',
    nameA: 'Асель',
    nameD: 'Дарья',
    buttonMainPage: 'Главная страница',
    buttonEditProfile: 'Профиль',
    buttonNewBoard: 'Новая доска',
    signOut: 'Выйти',
  },
};
export default i18Obj;
